### ISSUE TITLE
Gauge fields are overflowing outside of card

### ISSUE THREAD

**Issue by Mischa0x** [Popcorn-Limited/gauges#11]
On my Macbook 13'", this is what i see when I open the card. The contracts addresses are overflowing outside of the card

<img width="1112" alt="Screenshot 2023-08-16 at 11 17 09 AM" src="https://github.com/Popcorn-Limited/gauges/assets/88731911/0cddca44-d59e-4921-9628-071997a928ad">

**Comment by RedVeil** [comment]
fixed

**Comment by Mischa0x** [comment]
Im still seeing this:

<img width="1077" alt="Screenshot 2023-08-16 at 12 09 39 PM" src="https://github.com/Popcorn-Limited/gauges/assets/88731911/c96084fe-38fa-44df-b246-60ac49fea4b9">
